name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Enable Corepack and pnpm
        run: |
          corepack enable
          echo "✅ pnpm version: $(pnpm -v)"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Run tests (if available)
        run: pnpm run test || echo "✅ No tests found or skipped."


  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Enable Corepack and pnpm
        run: |
          corepack enable
          echo "✅ pnpm version: $(pnpm -v)"

      - name: Install dependencies
        run: pnpm install

      - name: Lint code with Biome
        run: pnpm run biome


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Enable Corepack and pnpm
        run: |
          corepack enable
          echo "✅ pnpm version: $(pnpm -v)"

      - name: Install dependencies
        run: pnpm install

      - name: Build for Production
        run: pnpm run build

      - name: Deploy
        run: echo "🚀 Add your deployment steps here"
